title: Passer Article Archive
iconURL: assets/default-icon.png

lang: zh-CN

# for a clean URL
permalink: :slug

social:
  twitter: 
  github: takuron

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14